cabal-version:      3.0
name:               haskproto
version:            0.1.0.0
license:            NONE
build-type:         Simple

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  HaskProto.Schema
                    , HaskProto.Parser
                    , HaskProto.Validate
                    , HaskProto.Pretty
                    , HaskProto.Value
                    , HaskProto.Wire
                    , HaskProto.Json
    hs-source-dirs:   src
    build-depends:    base ^>=4.18.3.0,
                      aeson,
                      bytestring,
                      containers,
                      mtl,
                      scientific,
                      text,
                      vector
    default-language: Haskell2010

executable haskproto
    import:           warnings
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base ^>=4.18.3.0,
                      bytestring,
                      haskproto
    default-language: Haskell2010
